### PR TITLE
Various small updates

### PR DESCRIPTION
**Pull request by neilb**
Hi Fayland,

I've just started using Todoist, and was very happy to write your module. I've written a basic command-line tool, which I used to import things into todoist. Would you be open to adding that to the dist? if so I'll send a pull request for that, once it's in a decent state (just a hack right now). I'll minimise the number of additional dependencies.

Anyway, here's a first bunch of changes, mainly documentation tweaks.

Cheers,
Neil

### CODE REVIEW

**Comment by fayland** [comment]
that's great. if you want co-maint that, let me know. Thanks

**Comment by fayland** [comment]
@neilbowers FYI Added NEILB to co-maintainers of Net::Todoist.

**Comment by neilb** [comment]
Cheers!

**Comment by neilb** [comment]
Shall I go ahead and release these changes? I'll make some other doc changes as I'm working on my script.

**Comment by fayland** [comment]
Yes please do whatever you want. I trust you. Thanks

**Comment by neilb** [comment]
> Yes please do whatever you want. I trust you.

That's very kind of you, thanks. I've just done a release with these changes. I hope I can repay your trust! :-)

**Pull request merged**
